---
- hosts: all
  become: yes
  vars:
    kafka:
      version: 0.10.1.1
      mirror: https://archive.apache.org/dist/kafka
      dataDir: /var/lib/kafka
      installDir: "/opt"
      serverMemory: "512M"
      scalaVersion: 2.11
    zookeeper:
      ip: "192.168.5.100:2181,192.168.5.100:2181"
      
  tasks:
    - name: Java | Add repo for java 8
      apt_repository: repo='ppa:webupd8team/java' state=present

    - name: Java | Set licence selected
      shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
      sudo: yes

    - name: Java | Set licence seen
      shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
      sudo: yes

    - name: Java | Install
      apt: name=oracle-java8-installer state=latest update-cache=yes force=yes
      sudo: yes
      
      # Kafka
    - name: Kafka | Set internal variable kafka_name
      set_fact: kafka_name="kafka_{{kafka.scalaVersion}}-{{kafka.version}}"
    - name: Kafka | Set internal variable kafka_dir
      set_fact: kafka_dir="{{kafka.installDir}}/{{kafka_name}}"
      
    - name: Kafka | Download
      get_url:
        url: "{{kafka.mirror}}/{{kafka.version}}/{{kafka_name}}.tgz"
        dest: "/tmp"
        
    - name: Kafka | Ensure tar is extracted
      command: tar xzf /tmp/{{kafka_name}}.tgz chdir="{{kafka.installDir}}"

    - name: Kafka | Set Server config
      template:
        src: "templates/server.properties"
        dest: "{{kafka_dir}}/config"

    - name: Kafka | Set Server Startup
      template:
        src: "templates/kafka-server-start.sh"
        dest: "{{kafka_dir}}/bin"
        mode: 0755

    - name: Kafka | Set init.d environment
      template:
        src: "templates/kafka"
        dest: "/etc/init.d/"
        mode: 0755

    - name: Kafka | Run service
      service: name=kafka state=started enabled=yes

    - name: Kafka | Configure autostart
      file:
        src: /etc/init.d/kafka
        dest: /etc/rc3.d/S99kafka
        state: link
